# Generated by Django 5.0.1 on 2024-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название носоти')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание новости')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/news/', verbose_name='Изображение')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория')),
                ('numberParticipants', models.IntegerField(blank=True, null=True, verbose_name='Количество участников')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание новости')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Изображение')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата')),
                ('numberParticipants', models.IntegerField(blank=True, null=True, verbose_name='Количество участников')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адресс')),
                ('programEvent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Программа мероприятия')),
                ('organizers', models.ManyToManyField(blank=True, to='UserProfile.organizers', verbose_name='Орагнизаторы')),
                ('speakers', models.ManyToManyField(blank=True, to='UserProfile.speaker', verbose_name='Спикеры')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
