# Generated by Django 5.0.1 on 2024-01-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0003_alter_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='programEvent',
            field=models.TextField(blank=True, null=True, verbose_name='Программа мероприятия'),
        ),
    ]
