# Generated by Django 5.0.1 on 2024-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0004_alter_events_programevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Изображение для мероприятия'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/', verbose_name='Изображение для мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Изображение для карточки'),
        ),
    ]
