# Generated by Django 5.0.1 on 2024-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0005_events_photo2_news_photo2_alter_events_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество очков за мероприятие'),
        ),
    ]
