# Generated by Django 5.0.1 on 2024-01-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='photo',
        ),
        migrations.AlterField(
            model_name='organizers',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
