# Generated by Django 5.0.1 on 2024-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_alter_organizers_user_alter_speaker_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
