# Generated by Django 5.0.1 on 2024-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participatingEvents',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Мои мероприятия'),
        ),
    ]
